---

name: Bug Report
description: Please do not use bug reports for support issues.
title: "[Bug]: "
labels: ['status:awaiting-triage', 'type:bug']
body:
  - type: markdown
    attributes:
      value: |
        **THIS IS NOT THE PLACE TO ASK FOR SUPPORT!** Please use [Discord](https://unmanic.app/discord) for support issues.
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List each action required in order to reproduce the issue.
      placeholder: |
        1. First Step '...'
        2. Second Step '...'
        3. So on '...'
        4. See error
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Provide screenshots to help explain your problem.
  - type: textarea
    id: relevant
    attributes:
      label: Relevant Settings
      description: Include all settings/configuration that are relevant to your setup.
      placeholder: |
        - eg. How Unmanic is installed.
        - eg. Configuration of your Docker container (if Unmanic is installed with Docker).
        - eg. Python version (if not installed with Docker).
        - eg. Configuration of the library within Unmanic.
  - type: input
    id: version
    attributes:
      label: Version
      description: The version is displayed under **Settings > Help & Support**
    validations:
      required: true
  - type: textarea
    id: platform
    attributes:
      label: Platform
      description: |
        Detail the host OS platform, version and software versions.
      placeholder: |
          - eg. OS / Linux Distro.
          - eg. Python version (if not using Docker).
          - eg. Any other tool versions such as FFmpeg, Comskip, Filebot, etc.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output. 
        This will be automatically formatted into code, so no need for backticks.
      render: Shell
  - type: markdown
    attributes:
      value: |
        Make sure to close your issue when it's solved! If you found the solution yourself please comment so that others benefit from it.
